//
//  AddressValidation.swift
//  21-DOT-DEV/swift-bitcoinkernel
//
//  Copyright (c) 2026-present Timechain Software Initiative, Inc.
//  Distributed under the MIT software license
//
//  See the accompanying file LICENSE for information
//

/// Result of `validateaddress`.
///
/// When `isvalid` is false, only `isvalid` is populated.
///
/// - Note: Targets Bitcoin Core v31.x.
public struct AddressValidation: Codable, Sendable, Equatable {
    /// Whether the address is valid.
    public let isvalid: Bool
    /// The bitcoin address validated.
    public let address: String?
    /// The hex-encoded output script generated by the address.
    public let scriptPubKey: String?
    /// Whether the key is a script.
    public let isscript: Bool?
    /// Whether the address is a witness address.
    public let iswitness: Bool?
    /// The version number of the witness program.
    public let witnessVersion: Int?
    /// The hex value of the witness program.
    public let witnessProgram: String?

    enum CodingKeys: String, CodingKey {
        case isvalid, address, scriptPubKey, isscript, iswitness
        case witnessVersion = "witness_version"
        case witnessProgram = "witness_program"
    }
}
