//
//  BlockWithPrevouts.swift
//  21-DOT-DEV/RPCModels
//
//  Copyright (c) 2024 Timechain Software Initiative
//  Distributed under the MIT software license
//
//  See the accompanying file LICENSE for information
//

/// A block with full transaction details and prevout info (verbosity 3, v28+).
///
/// Returned by `getblock` with verbosity=3. Each vin includes the prevout
/// scriptPubKey and value from the spending output.
public struct BlockWithPrevouts: Codable, Sendable, Equatable {
    public let hash: String
    public let confirmations: Int
    public let size: Int
    public let strippedSize: Int
    public let weight: Int
    public let height: Int
    public let version: Int
    public let versionHex: String
    public let merkleRoot: String
    public let tx: [TransactionWithPrevout]
    public let time: UnixTimestamp
    public let medianTime: UnixTimestamp
    public let nonce: Int64
    public let bits: String
    public let target: String?
    public let difficulty: Double
    public let chainWork: String
    public let nTx: Int
    public let previousBlockHash: String?
    public let nextBlockHash: String?

    enum CodingKeys: String, CodingKey {
        case hash, confirmations, size, weight, height, version, versionHex, tx, nonce, bits, target, difficulty, nTx
        case strippedSize = "strippedsize"
        case merkleRoot = "merkleroot"
        case time
        case medianTime = "mediantime"
        case chainWork = "chainwork"
        case previousBlockHash = "previousblockhash"
        case nextBlockHash = "nextblockhash"
    }
}

/// A transaction with prevout information on each input (verbosity 3).
public struct TransactionWithPrevout: Codable, Sendable, Equatable {
    public let txid: String
    public let hash: String
    public let version: Int
    public let size: Int
    public let vsize: Int
    public let weight: Int
    public let locktime: Int64
    public let vin: [VinWithPrevout]
    public let vout: [Vout]
    public let hex: String?
}

/// A transaction input with prevout data (the output being spent).
public struct VinWithPrevout: Codable, Sendable, Equatable {
    public let txid: String?
    public let vout: Int?
    public let scriptSig: ScriptSig?
    public let coinbase: String?
    public let txinwitness: [String]?
    public let sequence: Int64
    public let prevout: Prevout?
}

/// The previous output being spent by an input (verbosity 3).
public struct Prevout: Codable, Sendable, Equatable {
    /// Whether this output was generated by a coinbase transaction.
    public let generated: Bool

    /// The block height of the previous output.
    public let height: Int

    /// The value in BTC.
    public let value: BTCAmount

    /// The scriptPubKey.
    public let scriptPubKey: ScriptPubKey
}
